app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */
Route::get('/', function () {
    return Redirect::to('BackLogin');
});
Route::get('BBanner', ['as' => 'Back.Banner', 'uses' => 'Reception\Reception\ReceptionController@Banner']);

Route::resource('BackLogin', 'admin\BackLoginController@index');

//vvvvvvvvvvvvvvvvv auth link vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Route::group(['middleware' => ['auth', 'sessiontimeout']], function () {
    Route::get('BackHome', ['as' => 'BackHome.index', 'uses' => 'admin\BackLoginController@Home',function(){
        return view('BackHome');
    }]);
    Route::group(['middleware' => ['acl']], function () {
        //^^^^^^^^^^^^^^^^基礎資料


        //log管理
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        //服務公告管理
        Route::resource('BackAnnouncementInformation', 'admin\PublicInformation\BackAnnouncementInformationController');
        //公告分類管理
        Route::resource('BackAnnouncementInformationClass', 'admin\PublicInformation\BackAnnouncementInformationClassController');
        //活動花絮
        Route::resource('BackBanner', 'admin\PublicInformation\BackBannerController');
        //塔位查詢
        Route::resource('BackTowerSelect', 'admin\TowerSelect\BackTowerSelectController');
        //ui
        Route::resource('BackUi', 'admin\Select\BackUiController');
        Route::resource('api_select', 'admin\Select\BackUiController@api_select');
        Route::get('api_select_data', ['as' => 'api_select_data', 'uses' => 'admin\Select\BackUiController@api_select_data']);
        Route::get('api_select_data_t', ['as' => 'api_select_data_t', 'uses' => 'admin\Select\BackUiController@api_select_data_t']);

        
        Route::get('api_select_data_s', ['as' => 'api_select_data_s', 'uses' => 'admin\Select\BackUiController@api_select_data_s']);
        //各類櫃位及牌位使用情形及數量統計  
        Route::resource('BackPaper', 'admin\Paper\BackPaperController');
        //各項收入統計
        Route::get('BackPaperShow', ['as' => 'BackPaperShow', 'uses' => 'admin\Paper\BackPaperController@table']);
        Route::resource('BackPaper', 'admin\Paper\BackPaperController');

        Route::resource('BackPaperMoneySum', 'admin\Paper\BackPaperMoneySumController');

        
        Route::get('BackPaperMoneySumShow', ['as' => 'BackPaperMoneySumShow', 'uses' => 'admin\Paper\BackPaperMoneySumController@table']);

        Route::get('BackPaperMoneyDetailSumShow', ['as' => 'BackPaperMoneyDetailSumShow', 'uses' => 'admin\Paper\BackPaperMoneyDetailSumController@table']);



        //各項新增收入及退費金額統計
        Route::resource('BackPaperMoneyDetail', 'admin\Paper\BackPaperMoneyDetailSumController');
        //牌位查詢
        Route::resource('BackTombstoneSelect', 'admin\Select\BackTombstoneSelectController');
        
        Route::get('BackTombstoneSelectChangeSelect', ['as' => 'BackTombstone.ChangeSelect', 'uses' => 'admin\Select\BackTombstoneSelectController@change_select']);

        //櫃位查詢
        Route::resource('BackCabinet', 'admin\Select\BackCabinetController');
        //貴為查詢條件變動
        Route::get('BackCabinetSelect', ['as' => 'BackCabinet.ChangeSelect', 'uses' => 'admin\Select\BackCabinetController@change_select']);
        Route::get('BackCabinetCalculate', ['as' => 'BackCabinet.BackCabinetCalculate', 'uses' => 'admin\CabinetAppliction\BackCabinetApplictionController@calculate']);
        Route::get('BackCabinetChangeCalculate', ['as' => 'BackCabinet.BackCabinetChangeCalculate', 'uses' => 'admin\CabinetAppliction\BackCabinetChangeApplictionController@change_calculate']);

        //圖片刪除
        Route::get('BackRemove', ['as' => 'Back.RemoveFile', 'uses' => 'admin\RemoveFileController@remove_file']);

        //帳號管理
        Route::resource('BackUserManagement', 'admin\Management\BackUserManagementController');
        //role管理
        Route::resource('BackRole', 'admin\management\role\BackRoleController'); 
        //程式註冊
        Route::resource('BackRoleControls', 'admin\Management\role\BackRoleControlsController'); 
        //角色維護
        Route::resource('BackProgramRegistration', 'admin\System\BackProgramRegistrationController');
        //選單註冊
        Route::resource('BackMenuClass', 'admin\System\BackMenuClassController');
        //櫃位管理
        Route::resource('BackCabinetSys', 'admin\CabinetSys\BackCabinetSysController');
        //櫃位管理ajax
        Route::get('BackCabinetSysAddClass',['as'=>'BackCabinetSys.AddClass','uses'=>'admin\CabinetSys\BackCabinetSysController@add_class']);

        Route::get('BackCabinetSysUpdateClass',['as'=>'BackCabinetSys.UpdateClass','uses'=>'admin\CabinetSys\BackCabinetSysController@update_class']);

        Route::get('BackCabinetSysDeleteClass',['as'=>'BackCabinetSys.DeleteClass','uses'=>'admin\CabinetSys\BackCabinetSysController@delete_class'] );

        Route::get('BackCabinetSysGetClass',['as'=>'BackCabinetSys.GetClass','uses'=>'admin\CabinetSys\BackCabinetSysController@get_class'] );

        Route::get('BackCabinetSysChangeStatus',['as'=>'BackCabinetSys.ChangeStatus','uses'=>'admin\CabinetSys\BackCabinetSysController@change_status'] );

        Route::get('BackApplictionC',['as'=>'BackApplictionC.delete','uses'=>'admin\BackApplictionController@c_delete'] );
        Route::get('BackApplictionT',['as'=>'BackApplictionT.delete','uses'=>'admin\BackApplictionController@t_delete'] );

        //櫃位管理ajax end
        //建立櫃位
        Route::get('BackCabinetSysCreateCabinetSys',['as'=>'BackCabinetSys.CreateCabinetSys','uses'=>'admin\CabinetSys\BackCabinetSysController@create_cabinet_sys'] );
        //建立櫃位end
        


        //櫃位開啟/關閉
        Route::get('BackCabinetSysCahngeStatus',['as'=>'BackCabinetSys.CahngeStatus','uses'=>'admin\CabinetSys\BackCabinetSysController@CahngeStatus'] );
        //櫃位費用管理
        Route::resource('BackCabinetCostDiscount', 'admin\CabinetCost\BackCabinetCostDiscountController');
        //取得層
        Route::get('BackCabinetCostDiscountGetRow',['as'=>'BackCabinetCostDiscount.GetRow','uses'=>'admin\CabinetCost\BackCabinetCostDiscountController@get_row']);

        Route::get('BackCabinetCostDiscountGetCost',['as'=>'BackCabinetCostDiscount.GetCost','uses'=>'admin\CabinetCost\BackCabinetCostDiscountController@get_cost']);
        //櫃位其他費用管理
        Route::resource('BackCabinetOtherCost', 'admin\CabinetCost\BackCabinetOtherCostController');
        //牌位管理
        Route::resource('BackTombstoneSys', 'admin\TombstoneSys\BackTombstoneSysController');
        //牌位費用設定
        Route::resource('BackTombstoneCost', 'admin\TombstoneCost\BackTombstoneCostController');
        //牌位其他費用設定
        Route::resource('BackTombstoneOtherCost', 'admin\TombstoneCost\BackTombstoneOtherCostController');

        //牌位開啟/關閉
        Route::get('BackTombstoneSysCahngeStatus',['as'=>'BackTombstone.CahngeStatus','uses'=>'admin\TombstoneSys\BackTombstoneSysController@cahnge_status'] );
        //牌位管理ajax
        Route::get('BackTombstoneSysAddClass',['as'=>'BackTombstone.AddClass','uses'=>'admin\TombstoneSys\BackTombstoneSysController@add_class']);

        Route::get('BackTombstoneSysUpdateClass',['as'=>'BackTombstone.UpdateClass','uses'=>'admin\TombstoneSys\BackTombstoneSysController@update_class']);

        Route::get('BackTombstoneSysDeleteClass',['as'=>'BackTombstone.DeleteClass','uses'=>'admin\TombstoneSys\BackTombstoneSysController@delete_class'] );

        Route::get('BackTombstoneSysGetClass',['as'=>'BackTombstone.GetClass','uses'=>'admin\TombstoneSys\BackTombstoneSysController@get_class'] );

        Route::get('BackTombstoneSysChangeStatus',['as'=>'BackTombstone.ChangeStatus','uses'=>'admin\TombstoneSys\BackTombstoneSysController@change_status'] );
        //牌位管理ajax end
        //建立櫃位
        Route::get('BackTombstoneSysCreateTombstoneSys',['as'=>'BackTombstone.CreateTombstone','uses'=>'admin\TombstoneSys\BackTombstoneSysController@create_sys'] );
        //建立櫃位end
        //逝者管理
        Route::resource('BackDeceasedManger', 'admin\DeceasedManger\BackDeceasedMangerController'); 
        //逝者管理
        Route::resource('BackDeceasedManger2', 'admin\DeceasedManger\BackDeceasedManger2Controller');
        Route::get('BackCabinetApplictionApi', 'admin\CabinetSys\BackCabinetSysController@api');
        Route::get('BackCabinetApplictionPdf', 'admin\CabinetAppliction\BackCabinetApplictionController@Pdf');
        Route::get('BackCabinetApplictionPdf2', 'admin\CabinetAppliction\BackCabinetApplictionController@Pdf2');
        Route::get('BackCabinetApplictionPdf3', 'admin\CabinetAppliction\BackCabinetApplictionController@Pdf3');
        Route::get('BackCabinetApplictionPdf4', 'admin\CabinetAppliction\BackCabinetApplictionController@Pdf4');

        Route::get('BackTombstoneApplictionPdf', 'admin\TombstoneAppliction\BackTombstoneApplictionController@Pdf');
        Route::get('BackTombstoneApplictionPdf2', 'admin\TombstoneAppliction\BackTombstoneApplictionController@Pdf2');
        Route::get('BackTombstoneApplictionPdf3', 'admin\TombstoneAppliction\BackTombstoneApplictionController@Pdf3');
        Route::get('BackTombstoneApplictionPdf4', 'admin\TombstoneAppliction\BackTombstoneApplictionController@Pdf4');


        Route::get('BackTombstoneSysApi', 'admin\TombstoneSys\BackTombstoneSysController@api');
        //櫃位申請流程
        Route::resource('BackCabinetAppliction', 'admin\CabinetAppliction\BackCabinetApplictionController'); 
        //櫃位異動申請流程
        Route::resource('BackCabinetChangeAppliction', 'admin\CabinetAppliction\BackCabinetChangeApplictionController'); 

resources/views/admin/Form/cabinet_sys_select.blade.php
<label>樓層：</label>
<select name="class_floor">
	<option value="1">01 1樓</option>
</select>	
<label>區域：</label>
<select name="class_area" id="area" onchange="change_sys_select('area')">
	@foreach($sys['area'] as $val)
	<option value="{{$val->id}}"
		@if(isset($request_data['area']))
			@if($request_data['area']==$val->id)
			selected 
			@endif
		@endif
		>{{$val->code.' '.$val->name}}</option>
	@endforeach
<option value="0">全部</option>
</select>

<label>排：</label>
<select name="class_layer" id="layer" onchange="change_sys_select('layer')">
	@foreach($sys['layer'] as $val)
	<option value="{{$val->id}}"
		@if(isset($request_data['layer']))
			@if($request_data['layer']==$val->id)
			selected 
			@endif
		@endif
		>{{$val->code.'排 '}}</option>
	@endforeach
<option value="0">全部</option>
</select>
<label>層：</label>
<select name="class_row" id="row" onchange="change_sys_select('row')">
	@foreach($sys['row'] as $val)
	<option value="{{$val->id}}"
		@if(isset($request_data['row']))
			@if($request_data['row']==$val->id)
			selected 
			@endif
		@endif
		>{{$val->code.'層 '}}</option>
	@endforeach
<option value="0">全部</option>
</select>
<label>方位：</label>
<select name="class_position" id="position" onchange="change_sys_select('position')">
	@foreach($sys['position'] as $key=> $val)
	<option value="{{$key}}"
	@if(isset($request_data['position']))
		@if($request_data['position']==$key)
		selected 
		@endif
	@endif
	>{{$val}}</option>
	@endforeach
<option value="0">全部</option>
</select>

resources/views/admin/Form/index.blade.php
@extends('layouts.admin.master')
@section('title','後臺管理')
@if(isset($id))
@section('Level',Breadcrumbs::render(Route::currentRouteName(),$id))
@else
@section('Level',Breadcrumbs::render(Route::currentRouteName()))
@endif
@section('content')
{!! Html::script(asset('js/ckeditor/ckeditor.js')) !!}
{!! Html::style(asset('backend/plugins/bootstrap-datepicker/css/datepicker3.css'))  !!}
{!! Html::script(asset('backend/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js'))!!}
{!! Html::script(asset('js/bootstrap-datetimepicker.js'))!!}
<link rel="stylesheet" href="{{asset('css/lightbox.min.css')}}">
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif
@if (isset($DetailName))
    <div class="alert alert-success">
        項目：{{ $DetailName}}
    </div>
@endif
{!!$FormTtile;!!}
{!!$FormBody;!!}

@stop
@section('script')

<script type="text/javascript">
   @if(isset($SelectValue1))
        $("#activity_id").val({!!$SelectValue1!!}).select2();
    @else
        $("#activity_id").val([]).select2();
    @endif
</script>
@stop

resources/views/admin/Form/t_cost_other.blade.php
@extends('layouts.admin.master')
@section('title','後臺管理')
@if(isset($id))
@section('Level',Breadcrumbs::render(Route::currentRouteName(),$id))
@else
@section('Level',Breadcrumbs::render(Route::currentRouteName()))
@endif
@section('content')
{!! Html::script(asset('js/ckeditor/ckeditor.js')) !!}
{!! Html::style(asset('backend/plugins/bootstrap-datepicker/css/datepicker3.css'))  !!}
{!! Html::script(asset('backend/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js'))!!}
{!! Html::script(asset('js/bootstrap-datetimepicker.js'))!!}
<style type="text/css">
ul, li {
    margin: 0;
    padding: 0;
    list-style: none;
}
.abgne_tab {
    clear: left;
    margin: 10px 0;
}
ul.tabs {
    width: 100%;
    height: 32px;
    border-bottom: 1px solid #999;
    border-left: 1px solid #999;
}
ul.tabs li {
    float: left;
    height: 31px;
    line-height: 31px;
    overflow: hidden;
    position: relative;
    margin-bottom: -1px;    /* 讓 li 往下移來遮住 ul 的部份 border-bottom */
    border: 1px solid #999;
    border-left: none;
    background: #e1e1e1;
}
ul.tabs li a {
    display: block;
    padding: 0 20px;
    color: #000;
    border: 1px solid #fff;
    text-decoration: none;
}
ul.tabs li a:hover {
    background: #ccc;
}
ul.tabs li.active  {
    background: #fff;
    border-bottom: 1px solid#fff;
}
ul.tabs li.active a:hover {
    background: #fff;
}
div.tab_container {
    clear: left;
    width: 100%;
    border: 1px solid #999;
    border-top: none;
    background: #fff;
}
div.tab_container .tab_content {
    padding: 20px;
}
div.tab_container .tab_content h2 {
    margin: 0 0 20px;
}


</style>
<div class="abgne_tab">
    <form action="{{route('BackTombstoneOtherCost.store')}}" method="POST" enctype="multipart/form-data" >
        {{ csrf_field() }}
        <ul class="tabs">
            <li><a href="#tab1">牌位其他費用設定</a></li>
        </ul>
        <div class="tab_container">
            
            <div id="tab1" class="tab_content">
                <input type="hidden" name="id" value="{{$Data->id}}">
                <label for="fname" class="">其他費用：</label>
                <input class="" width="100px" placeholder="" id="cost" name="cost" type="number" value="{{$Data->cost}}">
            </div>
        </div>
        
    </div>
    <div class="col-sm-12">
        <button class="btn btn-success" style="width: 100%" type="submit">儲存</button>
    </div>
    </form>
    @if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
    @endif
    <br>
    <br>
    <br>
    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
@stop

@section('script')

<script type="text/javascript">
 $(function(){
    // 預設顯示第一個 Tab
    var _showTab = 0;
    var $defaultLi = $('ul.tabs li').eq(_showTab).addClass('active');
    $($defaultLi.find('a').attr('href')).siblings().hide();
 
    // 當 li 頁籤被點擊時...
    // 若要改成滑鼠移到 li 頁籤就切換時, 把 click 改成 mouseover
    $('ul.tabs li').click(function() {
        // 找出 li 中的超連結 href(#id)
        var $this = $(this),
            _clickTab = $this.find('a').attr('href');
        // 把目前點擊到的 li 頁籤加上 .active
        // 並把兄弟元素中有 .active 的都移除 class
        $this.addClass('active').siblings('.active').removeClass('active');
        // 淡入相對應的內容並隱藏兄弟元素
        $(_clickTab).stop(false, true).fadeIn().siblings().hide();
 
        return false;
    }).find('a').focus(function(){
        this.blur();
    });
});
</script>
@stop

resources/views/admin/Form/tombstone_sys.blade.php
<div class="form-group">
    <label for="fname" class="col-sm-3 control-label">櫃位區域</label>
    <div class="col-sm-3">
        <select name="tombstone_class_aera" id="area"  onchange="change_sys_select('area');">
            @foreach($area as $key =>$value)
            <option value="{{$value->id}}"
                @if(isset($request_data['area']))
                    @if($request_data['area']==$value->id)
                        selected
                    @endif
                @endif
                >{{$value->code.' '.$value->name}}
            </option>
            @endforeach
        </select>
    </div>
    <label for="fname" class="col-sm-3 control-label">方位座向</label>
    <div class="col-sm-3">
        <select name="tombstone_class_position" id="position" onchange="change_sys_select('position');">
            @foreach($position as $key =>$value)
            <option value="{{$key}}"  
                @if(isset($request_data['position']))
                    @if($request_data['position']==$key)
                        selected
                    @endif
                @endif
            >{{$value}}</option>
            @endforeach
        </select>
    </div>
</div>
<div class="form-group">
    <label for="fname" class="col-sm-3 control-label">排</label>
    <div class="col-sm-3">
        <select name="tombstone_class_layer" id="layer" onchange="change_sys_select('layer');">
            @foreach($layer as $key =>$value)
             <option value="{{$value->id}}"
                 @if(isset($request_data['layer']))
                    @if($request_data['layer']==$value->id)
                        selected
                    @endif
                @endif
                >{{$value->code}}</option>
            @endforeach
        </select>
    </div>
    <label for="fname" class="col-sm-3 control-label">位子</label>
    <div class="col-sm-3">
        <select name="tombstone_class_seat" id='seat' onchange="change_sys_select('seat');">
            @foreach($seat as $key =>$value)
                <option value='{{$value->id}}'
                @if(isset($request_data['seat']))
                    @if($request_data['seat']==$value->id)
                            selected
                    @endif
                @endif
                >{{$value->code}}</option>
            @endforeach
        </select>
    </div>
</div>

<div class="form-group">
    <label for="fname" class="col-sm-3 control-label">現有空位</label>
    <div class="col-sm-9">
        <select name="tombstone_code" id='tombstone_code'>
            <option value="">沒有任何位置</option>
        </select>
        <a class="btn btn-success"  href="#pod" onclick="SaveData()">搜尋空位</a>
    </div>
</div>

resources/views/admin/Form/tombstone_sys_select.blade.php
<label>樓層：</label>
<select name="class_floor">
	<option value="1">1樓</option>
</select>	
<label>區域：</label>
<select name="class_area" id="area" onchange="change_sys_select('area')">
	<option value="0">無</option>
	@foreach($sys['area'] as $val)
	<option value="{{$val->id}}"
		@if(isset($request_data['area']))
			@if($request_data['area']==$val->id)
			selected 
			@endif
		@endif
		>{{$val->code.' '.$val->name}}</option>
	@endforeach
</select>

<label>排：</label>
<select name="class_layer" id="layer" onchange="change_sys_select('layer')">
	<option value="0">無</option>
	@foreach($sys['layer'] as $val)
	<option value="{{$val->id}}"
		@if(isset($request_data['layer']))
			@if($request_data['layer']==$val->id)
			selected 
			@endif
		@endif
		>{{$val->code.'排 '}}</option>
	@endforeach
</select>
<label>方位：</label>
<select name="class_position" id="position" onchange="change_sys_select('position')">
	@foreach($sys['position'] as $key=> $val)
	<option value="{{$key}}"
	@if(isset($request_data['position']))
		@if($request_data['position']==$key)
		selected 
		@endif
	@endif
	>{{$val}}</option>
	@endforeach
</select>